### ISSUE TITLE
rstar with u32, u64, ...

### ISSUE THREAD

**Issue by w14** [georust/rstar#147] opened 2023-12-28 23:06 UTC
The train `RTreeNum` requires `Signed`.[source](https://docs.rs/rstar/latest/rstar/trait.RTreeNum.html). This doesn't work when you try to create an r-tree with points (u32, u32), or other unsigned ints. 

You cannot implement Signed on u32, u64...because you can only implement traits in the file of the trait or the implemented object. Can you relax this assumption or add a workaround? I do not want the performance overhead of boxing or converting u32s.

**Comment by adamreichold** [comment] 2023-12-29 08:25
> You cannot implement Signed on u32, u64...because you can only implement traits in the file of the trait or the implemented object. Can you relax this assumption or add a workaround? I do not want the performance overhead of boxing or converting u32s.

If you want to workaround this, you already can by using a newtype wrapper `struct MyU32(u32);` on which you can implement any traits.

That said, the implementations of the various algorithms themselves currently make use of signedness where appropriate, so this is not something that can be relaxed without functional fallout.

**Comment by adamreichold** [comment] 2023-12-29 08:26
Duplicate of #129

**Closed by adamreichold** 2023-12-29 08:26 UTC
