### ISSUE TITLE
Need to use different types for Point::Scalar and square

### ISSUE THREAD

**Issue by stepancheg** [georust/rstar#145] opened 2023-12-24 01:31 UTC
If scalar is `i32`, distance squared is `i64`.

But currently `RTree` in operations like `RTree::locate_within_distance` assumes distance squared is the same type as scalar.

The workaround is for user to store data keyed by `i64` when data fits within `i32`. This is somewhat inefficient.

**Comment by adamreichold** [comment] 2023-12-24 09:07
Duplicate of #48

**Closed by adamreichold** 2023-12-24 09:07 UTC
